<a href="https://colab.research.google.com/github/ridhimapandey117/Python-Course-YT/blob/master/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a', 'b', 'c']
my_data  =[10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20,'c':30}

In [4]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [11]:
ser1 = pd.Series([1,2,3,4],['USA', 'Germany', 'USSR', 'Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [13]:
ser2 = pd.Series([1,2,5,4],['USA', 'Germany', 'Italy', 'Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [14]:
ser1['USA']

np.int64(1)

In [15]:
ser3 = pd.Series(data=labels)
print(ser3)

0    a
1    b
2    c
dtype: object

In [16]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [ ]:
#Dataframes