<a href="https://colab.research.google.com/github/ridhimapandey117/Python-Course-YT/blob/master/8/9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import pandas as pd

In [8]:
labels = ['a', 'b', 'c']
my_data  =[10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20,'c':30}

In [9]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [13]:
ser1 = pd.Series([1,2,3,4],['USA', 'Germany', 'USSR', 'Japan'])
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [14]:
ser2 = pd.Series([1,2,5,4],['USA', 'Germany', 'Italy', 'Japan'])
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [15]:
ser1['USA']

np.int64(1)

In [16]:
ser3 = pd.Series(data=labels)
print(ser3)

0    a
1    b
2    c
dtype: object

In [17]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

# Data Frames

In [19]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [20]:
np.random.seed(101) #any "random" output will always be the same
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
#How to use indexing to grab an object from this table
df['W'] #Will grab entire W column, this will become a series

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [22]:
df[['W', 'Z']] #Will grab multiple columns

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [23]:
df['new'] = df['W']*df['Y'] #can make a new column, can add whatever you want after the = sign
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  2.457737
B  0.651118 -0.319318 -0.848077  0.605965 -0.552198
C -2.018168  0.740122  0.528813 -0.589001 -1.067235
D  0.188695 -0.758872 -0.933237  0.955057 -0.176097
E  0.190794  1.978757  2.605967  0.683509  0.497204

In [24]:
df.drop('new',axis=1, inplace=True) #this is to remove a column, although you need to add axis= so it knows whether to drop a row (axis=0) or column (axis=1)
#This isn't a permanent change though unless you put inplace=True

In [25]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [26]:
df.loc['A'] #How to select rows

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [27]:
df.iloc[0] #Uses index position of rows to get them

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [28]:
df.loc[['A','B'], ['Y']] #will return specific rows/columns (put row then column in list)

          Y
A  0.907969
B -0.848077

In [29]:
booldf = df > 0 #prints out the table, does some conditional selection thing
df[booldf]

#prints out values if true and NaN if false
#can also straight up type df > 0 to get True if df > 0 or false otherwise

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [30]:
resultdf = df[df['W'] >0] #will only return the rows for which this statement is true
#In this, you get a data-frame in response rather than a series

In [31]:
resultdf['W']

A    2.706850
B    0.651118
D    0.188695
E    0.190794
Name: W, dtype: float64

In [32]:
df[df['W']>0]['X'] #Same thing as above, but done in one step

A    0.628133
B   -0.319318
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [33]:
boolser = df['W']>0
result = df[boolser]
mycols = ['Y', 'X']
result[mycols]

#will print all the values where the statement in the first line is true

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [34]:
#In the case of multiple conditions, include an & for and | for or
df[(df['W']>0) | (df['Y']>1)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [35]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [36]:
df.reset_index() #will add indexes to rows (but not permanently)
#to keep it permanently, add inplace=True in ()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [37]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [38]:
df['STATES'] = newind #Sets 'States' as a column with its own series values
df

          W         X         Y         Z STATES
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [65]:
df.set_index('States') = newind #Supposed to make a row, but it isn't working

KeyError: "None of ['States'] are in the columns"

In [40]:
import numpy as np
import pandas as pd

In [41]:
#Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside)) #makes each outside,inside pair into a tuple
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [42]:
df = pd.DataFrame(randn(6,2), hier_index, ['A', 'B'])
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [43]:
df.loc['G1']['A'] #How to call a subsection of a section

1    0.302665
2   -1.706086
3   -0.134841
Name: A, dtype: float64

In [49]:
df.index.names #Checks for name of indexes
df.index.names = ['Groups', "Num"]
df

                   A         B
Groups Num
G1     1    0.302665  1.693723
       2   -1.706086 -1.159119
       3   -0.134841  0.390528
G2     1    0.166905  0.184502
       2    0.807706  0.072960
       3    0.638787  0.329646

In [55]:
df.loc['G1'].loc[3]['A'] #Will taje value in A group, 3rd row, group G1; start from big and work ur way to small when calling for a value

np.float64(-0.13484072060601238)

In [63]:
df.xs(1,level='Num') #Use when you have a multilevel index AND want to get multiple rows from the table (opposed to df.loc where you can't get values from diff rows)

               A         B
Groups
G1      0.302665  1.693723
G2      0.166905  0.184502

# Missing Data

In [88]:
import numpy as np
import pandas as pd

In [91]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]} #np.nan means No Assigned Number
df = pd.DataFrame(d) #DataFrame makes a table of values, as opposed to df.Series which makes a table of a singular series
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [92]:
df.dropna(axis=1) #will drop any columns with missing values

   C
0  1
1  2
2  3

In [93]:
df.dropna() #will drop any rows with missing values

     A    B  C
0  1.0  5.0  1

In [94]:
df.dropna(thresh=2) #Can specify threshold (meaning at least how many non-values does it take before it gets removed)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [95]:
df.fillna(value='FILL') #replaces non-value with something else

      A     B  C
0   1.0   5.0  1
1   2.0  FILL  2
2  FILL  FILL  3

In [96]:
df['A'].fillna(value=df['A'].mean()) #replaces nan-value from column A with the average of the values in that column (bro what is this 😭)

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64



# Groupby

In [97]:
#Groupby lets you group together rows based off a column and combine them with an aggregate function

In [98]:
import numpy as np
import pandas as pd

In [102]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],'Sales':[200,120,340,124,243,350]}

In [103]:
df = pd.DataFrame(data)
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [111]:
byComp = df.groupby('Company') #groups all the company columns together
byComp.mean('Sales') #finds the mean of the sales of each company

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [112]:
byComp.sum('Sales') #will find the sum of all company sales

         Sales
Company
FB         593
GOOG       320
MSFT       464

In [115]:
byComp.sum('Sales').loc['FB'] #finds the sum of sales from FB specifically

Sales    593
Name: FB, dtype: int64

In [116]:
df.groupby('Company').sum('Sales').loc['FB'] #does same thing as line 115

Sales    593
Name: FB, dtype: int64

In [117]:
df.groupby('Company').count() #Counts instances of columns (like how there are two people in one company each and two sales for each company)

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [119]:
df.groupby('Company').max() #For strings, it'll take whatever comes last alphabetical order; for ints, it takes the greatest value (.min() does the oppposite)

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [123]:
df.groupby('Company').describe() #gives you information about each aggregated group (the percentages are part of the standard deviation stuff)
#can add .loc['GOOG'] or whateevr in the parenthesis to find a specific group

Sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64

In [124]:
import pandas as pd

In [133]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'], 'B':['B0', 'B1', 'B2', 'B3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']},index=[0,1,2,3])
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

#Merging, Joining, and Concatenation

Example #1

In [132]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'], 'B':['B4', 'B5', 'B6', 'B7'],'C':['C4','C5','C6','C7'],'D':['D4','D5','D6','D7']},index=[4,5,6,7])
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [131]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'], 'B':['B8', 'B9', 'B10', 'B11'],'C':['C8','C9','C10','C11'],'D':['D8','D9','D10','D11']},index=[8,9,10,11])
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# Concatenation
*   Concatenation glues together DataFrames
*   Dimensions should match alongside the axis you are concatenating on
*   Can use pd.concat for this

In [136]:
pd.concat([df1,df2,df3]) #Correct way

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [137]:
pd.concat([df1,df2,df3],axis=1) #Will put NaN in the positions where no value is specified

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

#Merge
* The merge functions lets you merge DataFrames together using .merge()
* Can specify 'on' keyword, but panda automatically does it w/o it

Example #1

In [141]:
left = pd.DataFrame({'key':['K0','K1', 'K2', 'K3'],'A':['A0', 'A1','A2','A3'],'B':['B0','B1','B2','B3']})
right = pd.DataFrame({'key':['K0','K1', 'K2', 'K3'],'C':['C0', 'C1','C2','C3'],'D':['D0','D1','D2','D3']})

In [146]:
pd.merge(left,right,on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

Example #2

In [147]:
left = pd.DataFrame({'key1':['K0','K0','K1','K2'],'key2':['K0','K0','K1','K2'],'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
right = pd.DataFrame({'key1':['K0','K0','K1','K2'],'key2':['K0','K0','K1','K2'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})

In [149]:
pd.merge(left,right) #even in cases of multiple same columns, it'll automatically merge them!!

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K0   K0  A0  B0  C1  D1
2   K0   K0  A1  B1  C0  D0
3   K0   K0  A1  B1  C1  D1
4   K1   K1  A2  B2  C2  D2
5   K2   K2  A3  B3  C3  D3

#Joining
* It's a method for joining two potentially differently-indexed DataFrames into a single result DataFrame

Example #1

In [150]:
left = pd.DataFrame({'A':['A0','A1','A2'],'B':['B0','B1','B2']}, index=['K0','K1','K2'])
right = pd.DataFrame({'C':['C0','C2','C3'],'D':['D0','D2','D3']}, index=['K0','K2','K3'])

In [151]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [153]:
left.join(right, how='outer') #outer means rows, inner means columns (this can be applied to all the other methods btw they just weren't working here)

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

#Operations

In [154]:
import numpy as np
import pandas as pd

In [156]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','jkl']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  jkl

In [161]:
df['col2'].unique() #will return all the unique values in whatever column you're looking at
df.loc[1].unique() #same thing but for rows

array([np.int64(2), np.int64(555), 'def'], dtype=object)

In [162]:
df['col2'].nunique() #gives you number of unique values in the column
df.loc[1].nunique() #same thing but for rows

3

In [163]:
df['col2'].value_counts() #returns a series of how many times a unique value occurs in the column

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [164]:
df[df['col1']>2] #returns a table that follows this conditi

#for more than one statement, wrap the statements in parenthesis and pair them with either & or |

   col1  col2 col3
2     3   666  ghi
3     4   444  jkl

In [165]:
def times2(x):
  return x*2

In [166]:
df['col1'].apply(times2) #.apply() lets you apply your own custom method to the table/series

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [169]:
df['col1'].apply(lambda x: x*2) #same thing as above but with a lambda expression

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [172]:
df.drop('col1', axis=1) #drops row/column (axis=0, means row; axis=1, means column)

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  jkl

In [175]:
df.columns #if u want to find out the names of all the columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [177]:
df.index #can also call index (rows)

RangeIndex(start=0, stop=4, step=1)

In [179]:
df.sort_values('col2') #can sort values based on a col (like how you sort things ascending and descending)

   col1  col2 col3
0     1   444  abc
3     4   444  jkl
1     2   555  def
2     3   666  ghi

In [180]:
df.isnull() #will return True if value in table is null and False otherwise

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [182]:
data = {'A':['foo', 'foo','foo','bar','bar','bar'],'B':['one','one','two','two','one','one'],'C':['x','y','x','y','x','y'],'D':[1,3,2,5,4,1]}
df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

# Data Input and Output

In [186]:
conda install sqlalchemy
conda install lxml
conda install html5lib
conda install BeautifulSoup4

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

SyntaxError: invalid syntax (2823742664.py, line 1)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)